# Generated by Django 5.0.1 on 2024-01-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('themename', models.TextField()),
                ('themecontent', models.TextField()),
                ('themeimg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
