# Generated by Django 5.0.1 on 2024-01-30 15:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genshinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='themecontent',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
