# Generated by Django 5.0.1 on 2024-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshinapp', '0002_alter_themes_themecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='themeimg',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
