# Generated by Django 5.0.1 on 2024-02-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshinapp', '0006_comments_commentimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genshinapp.themes'),
        ),
    ]
