# Generated by Django 5.0.1 on 2024-02-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshinapp', '0009_alter_comments_commentimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentimg',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
