# Generated by Django 5.0.1 on 2024-02-09 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshinapp', '0010_alter_comments_commentimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
